apiVersion: v1
kind: Namespace
metadata:
  name: frontend-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: frontend
          image: gauti12/frontend:latest  # Replace with your frontend image
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              value: "http://backend-service.backend-namespace.svc.cluster.local:5000"  # Backend service URL

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-namespace
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
