steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['cd backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['pwd']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/black-journal-436122-b5/todo-frontend:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/black-journal-436122-b5/todo-frontend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/frontend', 'todo-frontend=gcr.io/black-journal-436122-b5/todo-frontend:$SHORT_SHA', '--namespace=frontend']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
logsBucket: 'gs://my_bucket_pro'